import { IsBoolean, IsNotEmpty, IsOptional, IsString } from 'class-validator';

/**
 * DTO for linking a messaging channel to a user account.
 * In the simplified flow, only linkCode is supported.
 * Codes are generated by the bot when an unlinked user sends a message.
 */
export class LinkChannelDto {
  @IsString()
  @IsNotEmpty()
  linkCode: string;

  @IsOptional()
  @IsBoolean()
  force?: boolean;
}
