-- Migration: Simplify channel_link_codes table
-- Date: 2024-12-28
-- Description: Adapt channel_link_codes for the new code-only linking flow

-- ============================================================================
-- STEP 1: Add external_user_id column if it doesn't exist
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'channel_link_codes'
        AND column_name = 'external_user_id'
    ) THEN
        ALTER TABLE public.channel_link_codes
        ADD COLUMN external_user_id TEXT;
    END IF;
END $$;

-- ============================================================================
-- STEP 2: Drop redundant columns
-- ============================================================================

-- Remove 'token' column - JWT storage was redundant
ALTER TABLE public.channel_link_codes DROP COLUMN IF EXISTS token;

-- Remove 'user_id' column - not needed at code creation time
ALTER TABLE public.channel_link_codes DROP COLUMN IF EXISTS user_id;

-- ============================================================================
-- STEP 3: Ensure external_user_id is NOT NULL
-- ============================================================================

-- Delete any orphaned codes without external_user_id
DELETE FROM public.channel_link_codes WHERE external_user_id IS NULL;

-- Make the column NOT NULL
ALTER TABLE public.channel_link_codes ALTER COLUMN external_user_id SET NOT NULL;

-- ============================================================================
-- STEP 4: Add/update constraints and indexes
-- ============================================================================

-- Ensure code is unique
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'channel_link_codes_code_key'
  ) THEN
    ALTER TABLE public.channel_link_codes
    ADD CONSTRAINT channel_link_codes_code_key UNIQUE (code);
  END IF;
END $$;

-- Add unique constraint on channel + external_user_id for upsert
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'channel_link_codes_channel_external_user_id_key'
  ) THEN
    ALTER TABLE public.channel_link_codes
    ADD CONSTRAINT channel_link_codes_channel_external_user_id_key
    UNIQUE (channel, external_user_id);
  END IF;
END $$;

-- Add index for cleanup of expired codes
CREATE INDEX IF NOT EXISTS idx_channel_link_codes_expires
ON public.channel_link_codes(expires_at);

-- ============================================================================
-- STEP 5: Add comment documenting the new schema
-- ============================================================================

COMMENT ON TABLE public.channel_link_codes IS
'Temporary codes for linking messaging channels to user accounts.
Codes are generated by the bot when an unlinked user sends a message.
The code is consumed on the web when the user logs in and links their channel.

Columns:
- code: 8-char hex code (primary key)
- channel: telegram | whatsapp
- external_user_id: Platform-specific user ID from the bot message
- expires_at: Code expiration (10 minutes from creation)
- created_at: Timestamp of code creation
- used_at: Timestamp when code was consumed (NULL if not yet used)';
